# Site Settings
title: MK Portfolio - Modernist Theme
description: Personal portfolio and tech blog by Masato Kikukawa
baseurl: "/mk-portfolio"
url: "https://stackbeedash.github.io"

# Theme - Cayman via remote_theme
remote_theme: pages-themes/modernist@v0.2.0

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
